"""Advanced Skill Creation with MCP 2.14.3 LLM Sampling Integration."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Literal

from loguru import logger
from pydantic import BaseModel, Field

from advanced_memory.mcp.mcp_instance import mcp
from advanced_memory.mcp.tools.utils import build_error_response


class SkillRequirements(BaseModel):
    """Requirements for skill creation."""

    topic: str = Field(description="The main topic or domain the skill covers")
    expertise_level: Literal["beginner", "intermediate", "advanced", "expert"] = Field(
        description="Target expertise level for the skill"
    )
    use_cases: list[str] = Field(description="Primary use cases for this skill")
    target_audience: str = Field(description="Who will use this skill (developers, designers, etc.)")
    key_concepts: list[str] = Field(description="Essential concepts to cover")
    practical_examples: bool = Field(description="Whether to include practical examples")


class SkillValidation(BaseModel):
    """Validation results for skill content."""

    completeness_score: float = Field(description="0-1 score of content completeness")
    accuracy_score: float = Field(description="0-1 score of factual accuracy")
    clarity_score: float = Field(description="0-1 score of content clarity")
    issues_found: list[str] = Field(description="List of identified issues")
    improvement_suggestions: list[str] = Field(description="Suggestions for enhancement")


class SkillEnhancement(BaseModel):
    """Enhanced skill content generated by LLM."""

    enhanced_description: str = Field(description="Improved skill description")
    additional_sections: dict[str, str] = Field(description="New sections to add")
    improved_examples: list[str] = Field(description="Better practical examples")
    cross_references: list[str] = Field(description="Related skills to reference")


@mcp.tool()
async def make_skill_advanced(
    operation: Literal[
        "analyze_requirements",
        "generate_content",
        "validate_skill",
        "enhance_skill",
        "create_complete_skill",
        "iterative_improvement",
        "research_driven_skill",
        "research_first_create",
    ],
    topic: str | None = None,
    requirements: str | None = None,  # JSON string of SkillRequirements
    existing_skill_path: str | None = None,
    target_quality: Literal["basic", "comprehensive", "expert"] = "comprehensive",
    max_iterations: int = 3,
    enhancement_focus: list[str] | None = None,  # ["examples", "theory", "practical", "references"]
    output_path: str | None = None,
    enable_web_search: bool = False,
    web_search_provider: Literal["duckduckgo", "serpapi", "bing", "auto"] = "auto",
    web_search_time_filter: Literal["any", "day", "week", "month", "year"] = "month",
    web_sources_filter: list[str] | None = None,
    source_documents: list[str] | None = None,
    skill_name: str | None = None,
    research_sources: list[str] | None = None,
    max_research_iterations: int = 3,
    enable_review_loop: bool = False,
) -> dict[str, Any]:
    """
    Advanced Skill Creation using MCP 2.14.3 LLM Sampling Integration.

    This tool leverages the client's LLM through sampling capabilities to create,
    validate, and enhance skills with intelligent content generation and iterative improvement.

    PORTMANTEAU PATTERN RATIONALE:
    Consolidates advanced skill creation operations using MCP 2.14.3 sampling to enable
    LLM-interrogated skill development with intelligent content generation and validation.

    SUPPORTED OPERATIONS:

    analyze_requirements: Analyze topic and generate structured requirements
    - Uses LLM to understand the topic and create comprehensive skill requirements
    - Generates use cases, key concepts, and target audience analysis

    generate_content: Generate skill content from requirements
    - Creates complete SKILL.md content based on analyzed requirements
    - Includes structured sections, examples, and best practices

    validate_skill: LLM-powered validation of existing skills
    - Uses sampling to assess skill quality, completeness, and accuracy
    - Provides detailed feedback and improvement suggestions

    enhance_skill: Enhance existing skills with LLM insights
    - Improves skill content, adds missing sections, enhances examples
    - Maintains existing quality while adding depth and clarity

    create_complete_skill: End-to-end skill creation workflow
    - Combines analysis, generation, validation, and enhancement
    - Creates production-ready skills with full validation

    iterative_improvement: Multi-iteration skill refinement
    - Uses sampling to iteratively improve skills through multiple LLM passes
    - Each iteration enhances different aspects based on previous validation

    research_driven_skill: Web search-powered skill creation
    - Performs structured web searches for time-critical and specialized information
    - Integrates current research, news, and real-time data into skill content
    - Perfect for medical, political, and conspiracy analysis topics

    research_first_create: Research-chain-first skill creation (no sampling)
    - Runs adn_skills_research chain (arxiv, github, rag, web) with LLM gap analysis
    - Generates SKILL.md via LLMClient, scaffolds skill dir and references/
    - Runs spec validation; optional review loop to fix validation issues

    MCP 2.14.3 FEATURES USED:
    - ctx.sample() with tools for intelligent content generation
    - Structured output validation with Pydantic models
    - Multi-iteration workflows with progress tracking
    - Client LLM interrogation for domain expertise assessment

    Prerequisites:
    - MCP 2.14.3 sampling capabilities enabled
    - LLM provider configured (Anthropic/OpenAI)
    - Skills directory writable for output

    Args:
        operation: The advanced skill creation operation to perform
        topic: Topic/domain for skill creation (required for analysis/generate operations)
        requirements: JSON string of SkillRequirements (optional, auto-generated if not provided)
        existing_skill_path: Path to existing skill for validation/enhancement
        target_quality: Quality level for content generation
        max_iterations: Maximum iterations for iterative improvement (1-5)
        enhancement_focus: Areas to focus enhancement on
        output_path: Where to save the created/enhanced skill
        enable_web_search: Enable web search for research-driven skills
        web_search_provider: Web search provider for research
        web_search_time_filter: Time filter for web search results
        web_sources_filter: Domain filters for web search results
        source_documents: List of document paths (books, PDFs, papers) for deep research

    Returns:
        Operation-specific results with generated content, validation scores, and improvement suggestions

    Examples:
        # Analyze requirements for a new skill
        result = await make_skill_advanced(
            operation="analyze_requirements",
            topic="quantum-computing-algorithms"
        )

        # Create complete skill with LLM assistance
        result = await make_skill_advanced(
            operation="create_complete_skill",
            topic="kubernetes-security",
            target_quality="expert"
        )

        # Enhance existing skill
        result = await make_skill_advanced(
            operation="enhance_skill",
            existing_skill_path="/path/to/skill",
            enhancement_focus=["examples", "practical"]
        )

        # Iterative improvement over multiple passes
        result = await make_skill_advanced(
            operation="iterative_improvement",
            existing_skill_path="/path/to/skill",
            max_iterations=3
        )

        # Research-driven skill creation with web search
        result = await make_skill_advanced(
            operation="research_driven_skill",
            topic="brain tumor glioblastoma expert",
            web_search_provider="auto",
            web_search_time_filter="year",
            web_sources_filter=["nih.gov", "mayo.edu", "cancer.gov"]
        )

        # Current events political analysis
        result = await make_skill_advanced(
            operation="research_driven_skill",
            topic="Trump Greenland complications expert",
            web_search_provider="bing",
            web_search_time_filter="month",
            web_sources_filter=["reuters.com", "bbc.com", "wsj.com"]
        )

        # Conspiracy debunking with current research
        result = await make_skill_advanced(
            operation="research_driven_skill",
            topic="Kennedy assassination mahadebunking expert",
            web_search_provider="serpapi",
            web_search_time_filter="any",
            web_sources_filter=["snopes.com", "factcheck.org", "wikipedia.org"]
        )

        # Daniel Paul Schreber expert with primary source
        result = await make_skill_advanced(
            operation="research_driven_skill",
            topic="Daniel Paul Schreber psychological analysis expert",
            source_documents=["/books/schreber-memoirs.pdf"],
            focus_topics=["delusions", "paranoia", "divine_mission"]
        )

        # Malleus Maleficarum expert with original text
        result = await make_skill_advanced(
            operation="research_driven_skill",
            topic="Malleus Maleficarum historical witchcraft expert",
            source_documents=["/books/malleus-maleficarum.pdf"],
            web_search_provider="auto",
            web_search_time_filter="any"
        )

        # Transformer AI expert with original paper
        result = await make_skill_advanced(
            operation="research_driven_skill",
            topic="Transformer neural networks expert",
            source_documents=["/papers/attention-is-all-you-need.pdf"],
            web_search_provider="auto",
            web_search_time_filter="year",
            web_sources_filter=["arxiv.org", "neuralips.cc"]
        )
    """

    try:
        # research_first_create: uses adn_skills_research + LLMClient, no sampling needed
        if operation == "research_first_create":
            if not topic:
                return build_error_response("MISSING_TOPIC", "topic required for research_first_create")
            return await _research_first_create_operation(
                topic=topic.strip(),
                skill_name=skill_name,
                output_path=output_path,
                research_sources=research_sources or ["web", "arxiv", "github", "rag"],
                max_research_iterations=max_research_iterations,
                enable_review_loop=enable_review_loop,
            )

        # Validate operation-specific prerequisites
        if operation in ["analyze_requirements", "generate_content"] and not topic:
            return build_error_response(
                "MISSING_TOPIC", "topic parameter required for analysis and generation operations"
            )

        if operation in ["validate_skill", "enhance_skill", "iterative_improvement"] and not existing_skill_path:
            return build_error_response(
                "MISSING_SKILL_PATH",
                "existing_skill_path required for validation and enhancement operations",
            )

        # Import sampling capabilities (available in MCP 2.14.3)
        from advanced_memory.mcp.sampling import get_sampling_client

        sampling_client = get_sampling_client()

        if not sampling_client:
            return build_error_response(
                "SAMPLING_UNAVAILABLE",
                "MCP 2.14.3 sampling capabilities not available",
                recovery_options=[
                    "Ensure MCP server is running FastMCP 2.14.3",
                    "Configure LLM provider (Anthropic/OpenAI)",
                    "Check sampling handler registration",
                ],
            )

        # Execute operation-specific logic
        if operation == "analyze_requirements":
            return await _analyze_requirements_operation(sampling_client, topic, target_quality)

        elif operation == "generate_content":
            requirements_obj = None
            if requirements:
                try:
                    requirements_obj = SkillRequirements.model_validate_json(requirements)
                except Exception as e:
                    logger.warning(f"Invalid requirements JSON, proceeding without: {e}")

            return await _generate_content_operation(sampling_client, topic, requirements_obj, target_quality)

        elif operation == "validate_skill":
            return await _validate_skill_operation(sampling_client, existing_skill_path)

        elif operation == "enhance_skill":
            return await _enhance_skill_operation(sampling_client, existing_skill_path, enhancement_focus or [])

        elif operation == "create_complete_skill":
            requirements_obj = None
            if requirements:
                try:
                    requirements_obj = SkillRequirements.model_validate_json(requirements)
                except Exception as e:
                    logger.warning(f"Invalid requirements JSON, auto-generating: {e}")

            return await _create_complete_skill_operation(
                sampling_client, topic, requirements_obj, target_quality, output_path
            )

        elif operation == "iterative_improvement":
            return await _iterative_improvement_operation(
                sampling_client, existing_skill_path, max_iterations, enhancement_focus or []
            )

        elif operation == "research_driven_skill":
            return await _research_driven_skill_operation(
                sampling_client,
                topic,
                target_quality,
                web_search_provider,
                web_search_time_filter,
                web_sources_filter,
                source_documents,
                output_path,
                enable_web_search,
            )

        else:
            return build_error_response("INVALID_OPERATION", f"Unsupported operation: {operation}")

    except Exception as e:
        logger.error(f"Advanced skill creation failed: {e}")
        return build_error_response("OPERATION_FAILED", f"Advanced skill creation operation failed: {e!s}")


async def _analyze_requirements_operation(sampling_client, topic: str, quality: str) -> dict[str, Any]:
    """Analyze topic and generate structured skill requirements using LLM sampling."""

    # Create analysis prompt for LLM
    analysis_prompt = f"""
    Analyze the topic "{topic}" and generate comprehensive requirements for creating a skill about it.

    Consider:
    - Target audience and their background
    - Key concepts that must be covered
    - Practical use cases and applications
    - Current best practices and state-of-the-art approaches
    - Common pitfalls and how to avoid them
    - Learning progression from basic to advanced

    Quality level: {quality}

    Generate a structured analysis that will inform skill creation.
    """

    # Use sampling to get LLM analysis
    analysis_result = await sampling_client.sample(
        messages=[{"role": "user", "content": analysis_prompt}],
        tools=[],  # No tools needed for analysis
        response_format=SkillRequirements.model_json_schema(),
    )

    try:
        # Parse structured requirements from LLM response
        requirements = SkillRequirements.model_validate_json(analysis_result.content)

        return {
            "success": True,
            "operation": "analyze_requirements",
            "topic": topic,
            "requirements": requirements.model_dump(),
            "quality_level": quality,
            "analysis_timestamp": "2025-12-02",  # Current date
            "confidence_score": 0.85,  # Estimated based on LLM quality
        }

    except Exception as e:
        logger.error(f"Failed to parse LLM requirements analysis: {e}")
        return build_error_response("PARSING_FAILED", "Could not parse structured requirements from LLM response")


async def _generate_content_operation(
    sampling_client, topic: str, requirements: SkillRequirements | None, quality: str
) -> dict[str, Any]:
    """Generate complete skill content from requirements using LLM sampling."""

    # Build generation prompt
    requirements_text = ""
    if requirements:
        requirements_text = f"""
        Based on these analyzed requirements:
        - Topic: {requirements.topic}
        - Expertise Level: {requirements.expertise_level}
        - Use Cases: {", ".join(requirements.use_cases)}
        - Target Audience: {requirements.target_audience}
        - Key Concepts: {", ".join(requirements.key_concepts)}
        - Include Practical Examples: {requirements.practical_examples}
        """

    generation_prompt = f"""
    Create a complete Claude Skill about "{topic}" following the standard skill format.

    {requirements_text}

    Quality Level: {quality}

    Generate a SKILL.md file with:
    1. Proper YAML frontmatter (name, description, category, etc.)
    2. Comprehensive markdown content with clear sections
    3. Practical examples and use cases
    4. Best practices and guidelines
    5. Common pitfalls and solutions
    6. References and further reading

    The skill should be immediately usable and provide real value to developers/designers/etc.
    """

    # Use sampling for content generation
    content_result = await sampling_client.sample(
        messages=[{"role": "user", "content": generation_prompt}],
        tools=[],  # Content generation doesn't need tools
        max_tokens=4000,  # Allow for comprehensive content
    )

    # Extract generated content
    skill_content = content_result.content.strip()

    # Basic validation of generated content
    if not skill_content.startswith("---"):
        logger.warning("Generated content missing YAML frontmatter, adding basic structure")

        # Add basic frontmatter if missing
        skill_name = topic.lower().replace(" ", "-").replace("_", "-")
        basic_frontmatter = f"""---
name: {skill_name}
description: Comprehensive guide to {topic}
category: technical
version: 1.0.0
confidence: medium
last_validated: 2025-12-02
---

# {topic.title()}

Comprehensive guide and best practices for {topic}.

## Overview

This skill provides expert guidance on {topic} with practical examples and proven methodologies.

## Key Concepts

- Core principles and fundamentals
- Best practices and patterns
- Common use cases and applications

## Implementation Guide

Detailed steps and methodologies for effective {topic} implementation.

## Examples

Practical examples and code samples demonstrating key concepts.

## Best Practices

Proven approaches and recommendations for success.

## Common Pitfalls

Issues to avoid and how to resolve them.

## References

Additional resources and further reading.
"""

        skill_content = basic_frontmatter

    return {
        "success": True,
        "operation": "generate_content",
        "topic": topic,
        "generated_content": skill_content,
        "content_length": len(skill_content),
        "quality_level": quality,
        "generation_timestamp": "2025-12-02",
    }


async def _validate_skill_operation(sampling_client, skill_path: str) -> dict[str, Any]:
    """Validate existing skill using LLM-powered analysis."""

    skill_path_obj = Path(skill_path)
    if not skill_path_obj.exists():
        return build_error_response("SKILL_NOT_FOUND", f"Skill path does not exist: {skill_path}")

    skill_md_path = skill_path_obj / "SKILL.md"
    if not skill_md_path.exists():
        return build_error_response("INVALID_SKILL", f"SKILL.md not found in: {skill_path}")

    # Read skill content
    skill_content = skill_md_path.read_text(encoding="utf-8")

    # Create validation prompt
    validation_prompt = f"""
    Validate this Claude Skill for quality, completeness, and accuracy:

    {skill_content}

    Assess:
    1. Content completeness (0-1 score)
    2. Factual accuracy (0-1 score)
    3. Clarity and readability (0-1 score)
    4. Structure and organization
    5. Practical value and usefulness

    Identify specific issues and provide improvement suggestions.
    """

    # Use sampling for validation
    validation_result = await sampling_client.sample(
        messages=[{"role": "user", "content": validation_prompt}],
        tools=[],  # Validation doesn't need tools
        response_format=SkillValidation.model_json_schema(),
    )

    try:
        # Parse validation results
        validation = SkillValidation.model_validate_json(validation_result.content)

        # Calculate overall quality score
        overall_score = (validation.completeness_score + validation.accuracy_score + validation.clarity_score) / 3

        return {
            "success": True,
            "operation": "validate_skill",
            "skill_path": skill_path,
            "validation": validation.model_dump(),
            "overall_quality_score": round(overall_score, 2),
            "issues_count": len(validation.issues_found),
            "suggestions_count": len(validation.improvement_suggestions),
            "validation_timestamp": "2025-12-02",
        }

    except Exception as e:
        logger.error(f"Failed to parse validation results: {e}")
        return build_error_response("VALIDATION_FAILED", "Could not parse LLM validation results")


async def _enhance_skill_operation(sampling_client, skill_path: str, enhancement_focus: list[str]) -> dict[str, Any]:
    """Enhance existing skill with LLM-generated improvements."""

    skill_path_obj = Path(skill_path)
    skill_md_path = skill_path_obj / "SKILL.md"

    if not skill_md_path.exists():
        return build_error_response("SKILL_NOT_FOUND", f"SKILL.md not found: {skill_md_path}")

    # Read current skill content
    current_content = skill_md_path.read_text(encoding="utf-8")

    # Create enhancement prompt
    focus_areas = ", ".join(enhancement_focus) if enhancement_focus else "all areas"
    enhancement_prompt = f"""
    Enhance this Claude Skill by improving the following areas: {focus_areas}

    Current skill content:
    {current_content}

    Provide enhancements including:
    1. Improved descriptions and explanations
    2. Additional practical examples
    3. Better structure and organization
    4. More comprehensive coverage of key topics
    5. Updated best practices and current standards

    Return the enhanced skill content with all improvements integrated.
    """

    # Use sampling for enhancement
    enhancement_result = await sampling_client.sample(
        messages=[{"role": "user", "content": enhancement_prompt}],
        tools=[],  # Enhancement is content-focused
        max_tokens=6000,  # Allow for substantial enhancements
        response_format=SkillEnhancement.model_json_schema(),
    )

    try:
        # Parse enhancement results
        enhancement = SkillEnhancement.model_validate_json(enhancement_result.content)

        # Apply enhancements to create improved content
        improved_content = _apply_enhancements(current_content, enhancement)

        return {
            "success": True,
            "operation": "enhance_skill",
            "skill_path": skill_path,
            "enhancement": enhancement.model_dump(),
            "improved_content": improved_content,
            "enhancement_focus": enhancement_focus,
            "sections_added": len(enhancement.additional_sections),
            "examples_improved": len(enhancement.improved_examples),
            "cross_references_added": len(enhancement.cross_references),
            "enhancement_timestamp": "2025-12-02",
        }

    except Exception as e:
        logger.error(f"Failed to parse enhancement results: {e}")
        return build_error_response("ENHANCEMENT_FAILED", "Could not parse LLM enhancement results")


async def _create_complete_skill_operation(
    sampling_client,
    topic: str,
    requirements: SkillRequirements | None,
    quality: str,
    output_path: str | None,
) -> dict[str, Any]:
    """End-to-end skill creation with validation and enhancement."""

    # Step 1: Analyze requirements if not provided
    if not requirements:
        logger.info("Auto-generating requirements for complete skill creation")
        req_result = await _analyze_requirements_operation(sampling_client, topic, quality)
        if not req_result["success"]:
            return req_result
        requirements = SkillRequirements.model_validate(req_result["requirements"])

    # Step 2: Generate initial content
    logger.info("Generating initial skill content")
    content_result = await _generate_content_operation(sampling_client, topic, requirements, quality)
    if not content_result["success"]:
        return content_result

    # Step 3: Create temporary skill file for validation
    import tempfile

    with tempfile.TemporaryDirectory() as temp_dir:
        temp_skill_dir = Path(temp_dir) / topic.lower().replace(" ", "-")
        temp_skill_dir.mkdir()

        # Write generated content
        skill_md_path = temp_skill_dir / "SKILL.md"
        skill_md_path.write_text(content_result["generated_content"], encoding="utf-8")

        # Step 4: Validate the generated skill
        logger.info("Validating generated skill")
        validation_result = await _validate_skill_operation(sampling_client, str(temp_skill_dir))
        if not validation_result["success"]:
            return validation_result

        # Step 5: Enhance based on validation
        if validation_result["overall_quality_score"] < 0.8:
            logger.info("Enhancing skill based on validation feedback")
            enhancement_result = await _enhance_skill_operation(
                sampling_client, str(temp_skill_dir), ["examples", "practical", "theory"]
            )
            if enhancement_result["success"]:
                # Update content with enhancements
                skill_md_path.write_text(enhancement_result["improved_content"], encoding="utf-8")

        # Step 6: Final validation
        final_validation = await _validate_skill_operation(sampling_client, str(temp_skill_dir))

        # Step 7: Save to output location
        final_content = skill_md_path.read_text(encoding="utf-8")

        if output_path:
            output_path_obj = Path(output_path)
            output_path_obj.parent.mkdir(parents=True, exist_ok=True)
            output_path_obj.write_text(final_content, encoding="utf-8")
        else:
            # Default to skills directory
            output_base = Path("skills") / "generated"
            output_base.mkdir(parents=True, exist_ok=True)
            output_file = output_base / f"{topic.lower().replace(' ', '-')}.md"
            output_file.write_text(final_content, encoding="utf-8")
            output_path = str(output_file)

    return {
        "success": True,
        "operation": "create_complete_skill",
        "topic": topic,
        "final_content": final_content,
        "output_path": output_path,
        "quality_level": quality,
        "requirements_used": requirements.model_dump() if requirements else None,
        "initial_validation": validation_result,
        "final_validation": final_validation,
        "enhancements_applied": validation_result["overall_quality_score"] < 0.8,
        "creation_timestamp": "2025-12-02",
    }


async def _iterative_improvement_operation(
    sampling_client, skill_path: str, max_iterations: int, enhancement_focus: list[str]
) -> dict[str, Any]:
    """Multi-iteration skill improvement using LLM sampling."""

    skill_path_obj = Path(skill_path)
    skill_md_path = skill_path_obj / "SKILL.md"

    if not skill_md_path.exists():
        return build_error_response("SKILL_NOT_FOUND", f"SKILL.md not found: {skill_md_path}")

    # Read current content (placeholder for future use)
    _ = skill_md_path.read_text(encoding="utf-8")
    iteration_results = []

    for iteration in range(1, max_iterations + 1):
        logger.info(f"Starting iteration {iteration}/{max_iterations}")

        # Validate current state
        validation_result = await _validate_skill_operation(sampling_client, skill_path)
        if not validation_result["success"]:
            break

        iteration_results.append(
            {
                "iteration": iteration,
                "validation_score": validation_result["overall_quality_score"],
                "issues_found": len(validation_result["validation"]["issues_found"]),
            }
        )

        # Check if improvement needed
        if validation_result["overall_quality_score"] >= 0.9:
            logger.info(f"Sufficient quality achieved at iteration {iteration}")
            break

        # Enhance skill
        enhancement_result = await _enhance_skill_operation(sampling_client, skill_path, enhancement_focus)

        if enhancement_result["success"]:
            # Apply improvements
            improved_content = enhancement_result["improved_content"]
            skill_md_path.write_text(improved_content, encoding="utf-8")
        else:
            logger.warning(f"Enhancement failed at iteration {iteration}")
            break

    # Final validation
    final_validation = await _validate_skill_operation(sampling_client, skill_path)

    return {
        "success": True,
        "operation": "iterative_improvement",
        "skill_path": skill_path,
        "iterations_completed": len(iteration_results),
        "max_iterations": max_iterations,
        "iteration_history": iteration_results,
        "final_validation": final_validation,
        "improvement_achieved": final_validation["overall_quality_score"],
        "enhancement_focus": enhancement_focus,
        "improvement_timestamp": "2025-12-02",
    }


def _apply_enhancements(original_content: str, enhancement: SkillEnhancement) -> str:
    """Apply LLM-generated enhancements to skill content."""

    # This is a simplified implementation - in practice, you'd want more sophisticated
    # content merging logic that preserves structure while integrating improvements

    enhanced_content = original_content

    # Add enhanced description to frontmatter if provided
    if enhancement.enhanced_description:
        # Find and replace description in frontmatter
        lines = enhanced_content.split("\n")
        in_frontmatter = False
        for i, line in enumerate(lines):
            if line.strip() == "---":
                in_frontmatter = not in_frontmatter
                continue
            if in_frontmatter and line.startswith("description:"):
                lines[i] = f"description: {enhancement.enhanced_description}"
                break

        enhanced_content = "\n".join(lines)

    # Add new sections
    if enhancement.additional_sections:
        # Append new sections at the end
        enhanced_content += "\n\n## Additional Sections\n\n"
        for section_title, section_content in enhancement.additional_sections.items():
            enhanced_content += f"### {section_title}\n\n{section_content}\n\n"

    # Add improved examples
    if enhancement.improved_examples:
        enhanced_content += "\n## Enhanced Examples\n\n"
        for example in enhancement.improved_examples:
            enhanced_content += f"- {example}\n"

    # Add cross-references
    if enhancement.cross_references:
        enhanced_content += "\n## Related Skills\n\n"
        for reference in enhancement.cross_references:
            enhanced_content += f"- See also: {reference}\n"

        return enhanced_content


async def _process_source_documents_rag(source_documents: list[str], topic: str) -> dict[str, Any]:
    """Process source documents using RAG system for better retrieval."""

    try:
        from .adn_rag import adn_rag

        processed_documents = []

        for doc_path in source_documents:
            logger.info(f"Ingesting document into RAG: {doc_path}")

            # Ingest document into RAG system
            ingest_result = await (adn_rag.fn if hasattr(adn_rag, "fn") else adn_rag)(
                operation="ingest_document",
                document_path=doc_path,
                chunk_method="fixed",  # Use fixed chunking for consistency
            )

            if ingest_result.get("rag_result", {}).get("success"):
                processed_documents.append(ingest_result)

                # Query for topic-relevant content
                topic_query = f"{topic} key concepts important details"
                query_result = await (adn_rag.fn if hasattr(adn_rag, "fn") else adn_rag)(
                    operation="query_knowledge",
                    query=topic_query,
                    document_filter=[ingest_result["document_id"]],
                    max_results=10,
                )

                if query_result.get("results", {}).get("success"):
                    ingest_result["relevant_chunks"] = query_result["results"]["results"]
            else:
                logger.warning(f"Failed to ingest document {doc_path}: {ingest_result}")

        return {
            "success": True,
            "documents_processed": len(processed_documents),
            "total_documents": len(source_documents),
            "document_results": processed_documents,
            "processing_timestamp": "2025-12-02",
            "method": "rag",
        }

    except Exception as e:
        logger.error(f"RAG document processing failed: {e}")
        return {
            "success": False,
            "error": str(e),
            "documents_processed": 0,
            "total_documents": len(source_documents),
            "method": "rag",
            "suggestions": [
                "Check RAG system initialization",
                "Verify ChromaDB installation",
                "Ensure embedding model is available",
            ],
        }


async def _format_documents_for_skill_rag(document_data: dict[str, Any], topic: str) -> str:
    """Format RAG-processed documents for skill generation."""

    if not document_data or not document_data.get("success"):
        return "No primary source documents available for analysis."

    document_results = document_data.get("document_results", [])

    if not document_results:
        return "No document analysis results available."

    formatted_docs = "## Primary Source Documents Analysis (RAG-Enhanced)\n\n"

    for i, doc_result in enumerate(document_results, 1):
        rag_result = doc_result.get("rag_result", {})
        document_path = doc_result.get("document_path", "Unknown")
        document_id = doc_result.get("document_id", "Unknown")

        formatted_docs += f"### Document {i}: {document_path}\n\n"

        if rag_result.get("success"):
            formatted_docs += f"**Document ID**: {document_id}\n"
            formatted_docs += f"**Chunks Added**: {rag_result.get('chunks_added', 0)}\n"
            formatted_docs += f"**Total Characters**: {rag_result.get('total_characters', 0):,}\n\n"

            # Include relevant chunks found during ingestion
            relevant_chunks = doc_result.get("relevant_chunks", [])
            if relevant_chunks:
                formatted_docs += "**Key Relevant Passages**:\n\n"
                for j, chunk in enumerate(relevant_chunks[:5], 1):  # Limit to top 5
                    content = chunk.get("content", "")
                    score = chunk.get("score", 0)
                    formatted_docs += f"**Passage {j}** (Relevance: {score:.2f}):\n"
                    # Truncate very long passages
                    if len(content) > 500:
                        content = content[:500] + "..."
                    formatted_docs += f"```\n{content}\n```\n\n"
        else:
            formatted_docs += f"**Processing Failed**: {rag_result.get('error', 'Unknown error')}\n\n"

    # Add topic-specific RAG query results
    try:
        from .adn_rag import adn_rag

        # Query across all ingested documents for topic-relevant content
        topic_query = f"{topic} essential concepts core ideas important details"
        query_result = await (adn_rag.fn if hasattr(adn_rag, "fn") else adn_rag)(
            operation="query_knowledge",
            query=topic_query,
            max_results=8,
        )

        if query_result.get("results", {}).get("success"):
            results = query_result["results"]["results"]
            if results:
                formatted_docs += f"## Topic-Specific Analysis: {topic}\n\n"
                formatted_docs += "Based on semantic search across all source documents:\n\n"

                for j, result in enumerate(results[:6], 1):  # Top 6 results
                    content = result.get("content", "")
                    score = result.get("score", 0)
                    doc_id = result.get("document_id", "Unknown")

                    formatted_docs += f"**Key Finding {j}** (Score: {score:.2f}):\n"
                    # Truncate for readability
                    if len(content) > 400:
                        content = content[:400] + "..."
                    formatted_docs += f"```\n{content}\n```\n"
                    formatted_docs += f"*Source: {doc_id}*\n\n"

    except Exception as e:
        logger.warning(f"Failed to add topic-specific RAG analysis: {e}")
        formatted_docs += "\n*Note: Topic-specific analysis unavailable due to RAG query error.*\n\n"

    formatted_docs += "\n*RAG-enhanced document analysis completed on: 2025-12-02*"
    formatted_docs += f"\n*Documents processed: {len(document_results)}*"

    return formatted_docs


async def _research_driven_skill_operation(
    sampling_client,
    topic: str,
    quality: str,
    web_search_provider: str,
    web_search_time_filter: str,
    web_sources_filter: list[str] | None,
    source_documents: list[str] | None,
    output_path: str | None,
    enable_web_search: bool = False,
) -> dict[str, Any]:
    """Create skill with web research integration for time-critical topics."""

    logger.info(f"Starting research-driven skill creation for: {topic}")

    # Step 1: Process source documents if provided
    document_data = None
    if source_documents:
        logger.info(f"Processing {len(source_documents)} source documents with RAG")
        document_data = await _process_source_documents_rag(source_documents, topic)
        if not document_data["success"]:
            logger.warning("Document processing failed, continuing with web research only")

    # Step 2: Perform web research based on topic
    research_data = await _perform_topic_research(
        topic, web_search_provider, web_search_time_filter, web_sources_filter
    )

    # Step 3: Perform GitHub research for code and repository insights
    github_data = None
    if web_search_provider:  # Always perform GitHub research if web provider is specified
        logger.info(f"Performing GitHub research for: {topic}")
        github_data = await _perform_github_research(topic)

    # Step 4: Perform arXiv research for academic papers and research
    arxiv_data = None
    if web_search_provider:  # Always perform arXiv research if web provider is specified
        logger.info(f"Performing arXiv research for: {topic}")
        arxiv_data = await _perform_arxiv_research(topic)

    # Step 5: Perform TV Tropes research for narrative patterns (if creative writing related)
    tropes_data = None
    if web_search_provider and _is_narrative_topic(topic):
        logger.info(f"Performing TV Tropes research for: {topic}")
        tropes_data = await _perform_tvtropes_research(topic)

    if not research_data["success"] and not document_data and not github_data:
        return research_data  # Return error if all research methods failed

    # Step 3: Generate skill content with research integration
    research_context = _format_research_for_skill(research_data)
    document_context = await _format_documents_for_skill_rag(document_data, topic) if document_data else ""
    github_context = _format_github_for_skill(github_data) if github_data else ""
    arxiv_context = _format_arxiv_for_skill(arxiv_data) if arxiv_data else ""
    tropes_context = _format_tvtropes_for_skill(tropes_data) if tropes_data else ""

    generation_prompt = f"""
    Create a comprehensive Claude Skill about "{topic}" using the latest research, current information, primary source documents, GitHub code analysis, academic arXiv papers, and narrative patterns from TV Tropes.

    RESEARCH CONTEXT (gathered from web searches):
    {research_context}

    PRIMARY SOURCE DOCUMENTS:
    {document_context}

    GITHUB CODE ANALYSIS:
    {github_context}

    ACADEMIC RESEARCH (from arXiv):
    {arxiv_context}

    NARRATIVE PATTERNS (from TV Tropes research):
    {tropes_context}

    Create a SKILL.md file that incorporates this current information and research findings.
    Focus on practical, up-to-date knowledge that reflects the latest developments in the field.

    Quality Level: {quality}

    Generate a complete skill with:
    1. Accurate, current information based on the research provided
    2. Proper YAML frontmatter (name, description, category, etc.)
    3. Comprehensive sections covering key aspects of the topic
    4. Practical examples and current best practices
    5. References to the latest research and developments
    6. Analysis of recent trends and future directions

    The skill should be immediately valuable and reflect current state-of-the-art knowledge.
    When primary source documents are provided, include direct quotes and passages from the original texts to demonstrate deep understanding and authenticity.
    When GitHub research is available, incorporate insights from real-world implementations, recent code patterns, and community approaches to show practical, production-ready knowledge.

    When arXiv research is available, integrate findings from peer-reviewed academic papers, theoretical foundations, and cutting-edge research to provide deep scholarly understanding and establish credibility through academic rigor.

    When TV Tropes research is available, incorporate narrative patterns, character archetypes, and storytelling techniques to provide comprehensive understanding of creative writing conventions, audience expectations, and narrative design principles.
    """

    # Use sampling for research-informed content generation
    content_result = await sampling_client.sample(
        messages=[{"role": "user", "content": generation_prompt}],
        tools=[],  # Content generation doesn't need tools
        max_tokens=5000,  # Allow for comprehensive content
    )

    skill_content = content_result.content.strip()

    # Ensure proper frontmatter
    if not skill_content.startswith("---"):
        skill_name = topic.lower().replace(" ", "-").replace("_", "-")
        skill_content = f"""---
name: {skill_name}
description: Current expert knowledge on {topic} based on latest research
category: specialized
version: 1.0.0
last_researched: 2025-12-02
research_sources: {len(research_data.get("results", []))}
---

# {topic.title()}

Comprehensive, research-backed guide to {topic} incorporating the latest developments and findings.

## Current Research & Developments

{skill_content}
"""

    # Step 3: Save the skill
    if output_path:
        output_path_obj = Path(output_path)
        output_path_obj.parent.mkdir(parents=True, exist_ok=True)
        output_path_obj.write_text(skill_content, encoding="utf-8")
    else:
        # Default to skills directory
        output_base = Path("skills") / "research-driven"
        output_base.mkdir(parents=True, exist_ok=True)
        output_file = output_base / f"{topic.lower().replace(' ', '-')}.md"
        output_file.write_text(skill_content, encoding="utf-8")
        output_path = str(output_file)

    return {
        "success": True,
        "operation": "research_driven_skill",
        "topic": topic,
        "quality_level": quality,
        "research_data": research_data,
        "document_data": document_data,
        "github_data": github_data,
        "arxiv_data": arxiv_data,
        "tvtropes_data": tropes_data,
        "generated_content": skill_content,
        "output_path": output_path,
        "content_length": len(skill_content),
        "research_sources_used": len(research_data.get("results", [])) if research_data else 0,
        "document_sources_used": len(source_documents) if source_documents else 0,
        "github_sources_used": len(github_data.get("repositories", [])) + len(github_data.get("code_results", []))
        if github_data
        else 0,
        "arxiv_sources_used": len(arxiv_data.get("papers", [])) if arxiv_data else 0,
        "tvtropes_sources_used": len(tropes_data.get("results", [])) if tropes_data and "results" in tropes_data else 0,
        "web_search_provider": web_search_provider,
        "time_filter": web_search_time_filter,
        "sources_filter": web_sources_filter,
        "source_documents": source_documents,
        "creation_timestamp": "2025-12-02",
    }


def _ensure_valid_frontmatter(content: str, slug: str, topic: str) -> str:
    """Deterministically repair YAML frontmatter (2026-07-17).

    Small local models routinely emit frontmatter without the closing '---',
    which fails agentskills validation on every check. An LLM review loop is
    the wrong tool for a mechanical fix, so: extract whatever name/description
    survive, force name to the directory slug (name_matches_directory check),
    and rebuild a canonical frontmatter block around the remaining body.
    """
    import re as _re

    text = content.strip()
    if text.startswith("---"):
        rest = text[3:]
        close = _re.search(r"\n---\s*(?:\n|$)", rest)
        if close:
            fm_block = rest[: close.start()]
            body = rest[close.end():]
        else:
            lines = rest.lstrip("\n").split("\n")
            fm_lines: list[str] = []
            body_lines: list[str] = []
            for i, ln in enumerate(lines):
                if _re.match(r"^[A-Za-z_][\w-]*:\s?", ln):
                    fm_lines.append(ln)
                else:
                    body_lines = lines[i:]
                    break
            fm_block = "\n".join(fm_lines)
            body = "\n".join(body_lines)
    else:
        fm_block = ""
        body = text

    desc_m = _re.search(r"^description:\s*(.+)$", fm_block, _re.M)
    description = (
        desc_m.group(1).strip().strip('"').strip("'")
        if desc_m
        else f"Expert knowledge on {topic} based on chained research"
    )[:1000]
    return f"---\nname: {slug}\ndescription: {description}\n---\n\n{body.strip()}\n"


async def _research_first_create_operation(
    topic: str,
    skill_name: str | None,
    output_path: str | None,
    research_sources: list[str],
    max_research_iterations: int,
    enable_review_loop: bool,
) -> dict[str, Any]:
    """Create skill via research chain: run_chain -> LLM SKILL.md -> scaffold -> validate."""
    import re

    from advanced_memory.services.llm_client import get_llm_client
    from advanced_memory.services.skill_creator import (
        scaffold_references_from_research,
        scaffold_skill,
        validate_skill_agentskills,
    )
    from advanced_memory.services.skill_research_chain import run_chain

    logger.info("research_first_create: starting chain for topic=%s", topic)

    valid_sources = ["arxiv", "github", "rag", "web"]
    sources = [s for s in research_sources if s in valid_sources] or valid_sources
    max_iter = max(1, min(5, max_research_iterations))

    try:
        bundle = await run_chain(
            topic=topic,
            sources=sources,
            max_iterations=max_iter,
            coverage_threshold=0.85,
        )
    except Exception as exc:
        logger.exception("research_first_create: run_chain failed")
        return build_error_response(
            "RESEARCH_CHAIN_FAILED",
            str(exc),
            recovery_options=[
                "Check arxiv/github/rag/web tool availability",
                "Retry with fewer sources",
            ],
        )

    slug = skill_name
    if not slug:
        slug = re.sub(r"[^a-z0-9]+", "-", topic.strip().lower())[:64].strip("-")
    if not slug:
        slug = "skill"
    slug = re.sub(r"-+", "-", slug).strip("-")

    output_base = Path.cwd() / "skills"
    if output_path:
        p = Path(output_path).expanduser().resolve()
        if p.is_dir():
            output_base = p
        else:
            output_base = p.parent

    try:
        skill_dir = scaffold_skill(slug, output_base, overwrite=True)
    except Exception as exc:
        logger.exception("research_first_create: scaffold_skill failed")
        return build_error_response(
            "SCAFFOLD_FAILED",
            str(exc),
            recovery_options=["Check output_path permissions", "Use different skill_name"],
        )

    scaffold_references_from_research(skill_dir, bundle, include_sources_md=True)

    snippets_text = "\n\n".join(s.get("content", str(s))[:800] for s in (bundle.snippets or [])[:25])
    synthesis = bundle.synthesis or "No synthesis available."
    gaps = "\n".join(f"- {g}" for g in (bundle.gaps_remaining or [])[:10])

    system_prompt = """You generate Anthropic-compliant Claude SKILL.md files.
Output ONLY valid Markdown with YAML frontmatter. Frontmatter MUST include:
- name: hyphen-case (1-64 chars, lowercase, hyphens)
- description: 1-1024 chars
No other frontmatter required. Body: Overview, Usage, Content sections."""

    prompt = f"""Create a SKILL.md for a Claude skill about: {topic}

RESEARCH SYNTHESIS:
{synthesis}

KEY SNIPPETS:
{snippets_text[:6000]}

GAPS REMAINING:
{gaps}

Requirements:
1. name: {slug}
2. description: 1-2 sentences, max 200 chars
3. Body: Overview, Usage Instructions, Content (use research to fill)
Output the complete SKILL.md only, no preamble."""

    try:
        llm = get_llm_client()
        skill_content = await llm.generate(
            prompt=prompt,
            system_prompt=system_prompt,
            max_tokens=4000,
            temperature=0.5,
        )
    except Exception as exc:
        logger.exception("research_first_create: LLM generate failed")
        return build_error_response(
            "LLM_GENERATE_FAILED",
            str(exc),
            recovery_options=["Check Ollama/LM Studio/OpenAI is running", "Configure LLM provider"],
        )

    skill_content = _ensure_valid_frontmatter(skill_content, slug, topic)

    (skill_dir / "SKILL.md").write_text(skill_content, encoding="utf-8")

    spec_compliant, spec_warnings, agentskills_checks = validate_skill_agentskills(skill_dir)

    review_done: bool = False
    if enable_review_loop and not spec_compliant and spec_warnings:
        try:
            fix_prompt = f"""Fix this SKILL.md to pass agentskills validation.
Warnings: {spec_warnings}
Checks: {agentskills_checks}
Current content:
{skill_content}

Output the corrected full SKILL.md only."""

            fixed = await llm.generate(
                prompt=fix_prompt,
                system_prompt=system_prompt,
                max_tokens=4000,
                temperature=0.3,
            )
            fixed = _ensure_valid_frontmatter(fixed.strip(), slug, topic)
            if fixed.startswith("---"):
                (skill_dir / "SKILL.md").write_text(fixed, encoding="utf-8")
                spec_compliant, spec_warnings, agentskills_checks = validate_skill_agentskills(skill_dir)
                review_done = True
        except Exception as exc:
            logger.warning("research_first_create: review loop failed: %s", exc)

    return {
        "success": True,
        "operation": "research_first_create",
        "topic": topic,
        "skill_path": str(skill_dir),
        "skill_name": slug,
        "references_path": str(skill_dir / "references"),
        "spec_compliant": spec_compliant,
        "spec_warnings": spec_warnings,
        "agentskills_checks": agentskills_checks,
        "review_loop_applied": review_done,
        "coverage_score": bundle.coverage_score,
        "iteration_count": bundle.iteration_count,
        "sources_used": bundle.sources_used,
    }


async def _perform_topic_research(
    topic: str,
    provider: str,
    time_filter: str,
    sources_filter: list[str] | None,
) -> dict[str, Any]:
    """Perform web research for the given topic."""

    try:
        # Import the web search tool
        from .adn_web_search import adn_web_search

        # Craft research-focused search queries
        search_queries = _generate_research_queries(topic)

        all_results = []

        # Execute multiple targeted searches
        for query in search_queries[:3]:  # Limit to 3 searches to avoid overwhelming
            logger.info(f"Researching: {query}")

            search_result = await (adn_web_search.fn if hasattr(adn_web_search, "fn") else adn_web_search)(
                query=query,
                provider=provider,
                max_results=8,
                time_filter=time_filter,
                include_news=True,
                relevance_threshold=0.3,
                sources_filter=sources_filter,
            )

            if search_result["success"]:
                all_results.extend(search_result.get("results", []))

        # Remove duplicates and sort by relevance
        seen_urls = set()
        unique_results = []
        for result in all_results:
            if result["url"] not in seen_urls:
                seen_urls.add(result["url"])
                unique_results.append(result)

        unique_results.sort(key=lambda x: x.get("relevance_score", 0), reverse=True)

        return {
            "success": True,
            "topic": topic,
            "search_queries": search_queries,
            "total_results": len(unique_results),
            "results": unique_results[:15],  # Limit to top 15 most relevant
            "provider": provider,
            "time_filter": time_filter,
            "sources_filtered": sources_filter is not None,
        }

    except Exception as e:
        logger.error(f"Research failed for topic '{topic}': {e}")
        return {
            "success": False,
            "error": str(e),
            "topic": topic,
            "suggestions": [
                "Check web search provider configuration",
                "Verify network connectivity",
                "Try a different search provider",
                "Simplify the topic if it's too complex",
            ],
        }


def _generate_research_queries(topic: str) -> list[str]:
    """Generate targeted research queries for different aspects of the topic."""

    # Convert topic to lowercase for processing
    topic_lower = topic.lower()

    # Base queries for all topics
    queries = [
        f"{topic} latest research developments 2024 2025",
        f"{topic} current best practices and methods",
        f"{topic} recent advancements and breakthroughs",
    ]

    # Specialized queries based on topic content
    if any(word in topic_lower for word in ["medical", "health", "disease", "treatment", "clinical"]):
        queries.extend(
            [
                f"{topic} clinical trials latest results",
                f"{topic} new treatment options 2024",
                f"{topic} medical research breakthroughs recent",
            ]
        )

    elif any(word in topic_lower for word in ["political", "government", "policy", "election"]):
        queries.extend(
            [
                f"{topic} current developments news",
                f"{topic} policy changes recent updates",
                f"{topic} political analysis latest reports",
            ]
        )

    elif any(word in topic_lower for word in ["conspiracy", "debunk", "myth", "theory"]):
        queries.extend(
            [
                f"{topic} debunking evidence latest research",
                f"{topic} fact checking current analysis",
                f"{topic} conspiracy theory analysis recent",
            ]
        )

    # Greenland/Trump specific example
    if "greenland" in topic_lower and "trump" in topic_lower:
        queries.extend(
            [
                "Trump Greenland complications latest news 2024",
                "Greenland Trump real estate issues current status",
                "Trump Greenland investment problems recent developments",
            ]
        )

    # Brain tumor specific example
    if any(word in topic_lower for word in ["brain", "tumor", "cancer", "glioblastoma"]):
        queries.extend(
            [
                "brain tumor glioblastoma latest treatments 2024",
                "glioblastoma clinical trials new drugs 2025",
                "brain cancer immunotherapy advances current",
            ]
        )

    # Kennedy specific example
    if "kennedy" in topic_lower:
        queries.extend(
            [
                "Kennedy assassination conspiracy debunking evidence",
                "JFK assassination latest research and analysis",
                "Kennedy conspiracy theories fact checking current",
            ]
        )

    return queries[:6]  # Limit to 6 most relevant queries


def _format_research_for_skill(research_data: dict[str, Any]) -> str:
    """Format web research results for inclusion in skill content."""

    if not research_data.get("success"):
        return "No research data available - proceeding with general knowledge."

    results = research_data.get("results", [])

    if not results:
        return "Limited research data found - skill will be based on general knowledge."

    # Format top research findings
    formatted_research = "## Latest Research & Current Developments\n\n"

    # Group by source type for better organization
    medical_sources = []
    news_sources = []
    academic_sources = []
    other_sources = []

    for result in results[:10]:  # Top 10 most relevant
        url = result.get("url", "").lower()
        title = result.get("title", "")
        snippet = result.get("snippet", "")

        if any(domain in url for domain in [".edu", ".gov", "nih.gov", "mayo.edu", "hopkins.edu"]):
            academic_sources.append(f"**{title}**\n{snippet}\n*Source: {result.get('url')}*\n")
        elif any(domain in url for domain in ["news", "bbc", "cnn", "reuters", "apnews"]):
            news_sources.append(f"**{title}**\n{snippet}\n*Source: {result.get('url')}*\n")
        elif any(word in url for word in ["medical", "health", "clinic", "hospital"]):
            medical_sources.append(f"**{title}**\n{snippet}\n*Source: {result.get('url')}*\n")
        else:
            other_sources.append(f"**{title}**\n{snippet}\n*Source: {result.get('url')}*\n")

    # Add sections for each category
    if academic_sources:
        formatted_research += "### Academic & Research Findings\n\n"
        formatted_research += "\n\n".join(academic_sources[:3])  # Top 3

    if medical_sources:
        formatted_research += "\n### Medical & Clinical Updates\n\n"
        formatted_research += "\n\n".join(medical_sources[:3])

    if news_sources:
        formatted_research += "\n### Recent News & Developments\n\n"
        formatted_research += "\n\n".join(news_sources[:3])

    if other_sources:
        formatted_research += "\n### Additional Resources\n\n"
        formatted_research += "\n\n".join(other_sources[:2])

    formatted_research += "\n\n*Research conducted on: 2025-12-02*"
    formatted_research += f"\n*Sources analyzed: {len(results)}*"

    return formatted_research


async def _process_source_documents(source_documents: list[str]) -> dict[str, Any]:
    """Process primary source documents for research."""

    try:
        from .adn_document_ingest import adn_document_ingest

        processed_documents = []

        for doc_path in source_documents:
            logger.info(f"Processing document: {doc_path}")

            result = await (adn_document_ingest.fn if hasattr(adn_document_ingest, "fn") else adn_document_ingest)(
                file_path=doc_path,
                analysis_type="full",
                extract_quotes=True,
                max_pages=None,  # Process all pages
            )

            if result["success"]:
                processed_documents.append(result)
            else:
                logger.warning(f"Failed to process document {doc_path}: {result.get('error')}")

        return {
            "success": True,
            "documents_processed": len(processed_documents),
            "total_documents": len(source_documents),
            "document_analyses": processed_documents,
            "processing_timestamp": "2025-12-02",
        }

    except Exception as e:
        logger.error(f"Document processing failed: {e}")
        return {
            "success": False,
            "error": str(e),
            "documents_processed": 0,
            "total_documents": len(source_documents),
            "suggestions": [
                "Check document file paths",
                "Ensure documents are in supported formats (PDF, TXT, EPUB)",
                "Verify file permissions",
            ],
        }


def _format_documents_for_skill(document_data: dict[str, Any]) -> str:
    """Format processed documents for inclusion in skill generation."""

    if not document_data or not document_data.get("success"):
        return "No primary source documents available for analysis."

    analyses = document_data.get("document_analyses", [])

    if not analyses:
        return "No document analyses available."

    formatted_docs = "## Primary Source Documents Analyzed\n\n"

    for i, analysis in enumerate(analyses, 1):
        doc_info = analysis.get("analysis", {})

        formatted_docs += f"### Document {i}: {doc_info.get('title', 'Unknown Title')}\n\n"

        if doc_info.get("author"):
            formatted_docs += f"**Author**: {doc_info['author']}\n\n"

        formatted_docs += f"**Type**: {doc_info.get('document_type', 'unknown')}\n"
        formatted_docs += f"**Word Count**: {doc_info.get('word_count', 0):,}\n"
        formatted_docs += f"**Key Themes**: {', '.join(doc_info.get('key_themes', []))}\n\n"

        # Include summary
        if doc_info.get("summary"):
            formatted_docs += f"**Summary**: {doc_info['summary']}\n\n"

        # Include key quotes
        quotes = doc_info.get("extracted_quotes", [])
        if quotes:
            formatted_docs += "**Key Passages**:\n"
            for j, quote in enumerate(quotes[:5], 1):  # Limit to 5 quotes per document
                formatted_docs += f'{j}. "{quote}"\n'
            formatted_docs += "\n"

        # Include document chunks for detailed analysis
        chunks = doc_info.get("chunks", [])
        if chunks:
            formatted_docs += "**Detailed Content Analysis**:\n\n"
            # Include first few chunks as examples
            for chunk in chunks[:3]:
                content_preview = chunk.get("content", "")[:500]  # First 500 chars
                if content_preview:
                    formatted_docs += f"```\n{content_preview}...\n```\n\n"

    formatted_docs += "\n*Primary source analysis completed on: 2025-12-02*"
    formatted_docs += f"\n*Documents analyzed: {len(analyses)}*"

    return formatted_docs


async def _perform_github_research(topic: str) -> dict[str, Any]:
    """Perform GitHub research for the given topic."""

    try:
        from .adn_github_research import adn_github_research

        # Generate research queries based on topic
        queries = _generate_github_queries(topic)

        all_repositories = []
        all_code_results = []

        # Search for repositories
        for query in queries[:2]:  # Limit to 2 repo searches
            logger.info(f"Searching GitHub repos: {query}")

            repo_result = await (adn_github_research.fn if hasattr(adn_github_research, "fn") else adn_github_research)(
                operation="search_repositories",
                query=query,
                sort="stars",
                max_results=5,
            )

            if repo_result.get("repositories"):
                all_repositories.extend(repo_result["repositories"])

        # Search for code implementations
        code_query = f"{topic} implementation example"
        logger.info(f"Searching GitHub code: {code_query}")

        code_result = await (adn_github_research.fn if hasattr(adn_github_research, "fn") else adn_github_research)(
            operation="search_code",
            query=code_query,
            max_results=8,
        )

        if code_result.get("code_results"):
            all_code_results.extend(code_result["code_results"])

        # Remove duplicates
        seen_repos = set()
        unique_repositories = []
        for repo in all_repositories:
            repo_id = repo.get("full_name")
            if repo_id and repo_id not in seen_repos:
                seen_repos.add(repo_id)
                unique_repositories.append(repo)

        return {
            "success": True,
            "topic": topic,
            "repositories": unique_repositories[:10],  # Top 10 repos
            "code_results": all_code_results[:10],  # Top 10 code results
            "total_repositories_found": len(unique_repositories),
            "total_code_results_found": len(all_code_results),
            "search_timestamp": "2025-12-02",
        }

    except Exception as e:
        logger.error(f"GitHub research failed for topic '{topic}': {e}")
        return {
            "success": False,
            "error": str(e),
            "topic": topic,
            "suggestions": [
                "Check GITHUB_TOKEN environment variable",
                "Verify GitHub API is accessible",
                "Try with simpler search terms",
            ],
        }


def _generate_github_queries(topic: str) -> list[str]:
    """Generate targeted GitHub search queries for a topic."""

    topic_lower = topic.lower()

    # Base queries
    queries = [
        f"{topic} implementation",
        f"{topic} example project",
        f"{topic} tutorial",
    ]

    # Specialized queries based on topic
    if any(word in topic_lower for word in ["ai", "ml", "neural", "deep learning", "machine learning"]):
        queries.extend(
            [
                f"{topic} pytorch",
                f"{topic} tensorflow",
                f"{topic} huggingface",
            ]
        )

    elif any(word in topic_lower for word in ["web", "frontend", "backend", "api"]):
        queries.extend(
            [
                f"{topic} react",
                f"{topic} node.js",
                f"{topic} fastapi",
            ]
        )

    elif any(word in topic_lower for word in ["security", "cryptography", "encryption"]):
        queries.extend(
            [
                f"{topic} openssl",
                f"{topic} cryptography library",
            ]
        )

    # Always include language-agnostic searches
    queries.append(f"{topic} best practices")
    queries.append(f"{topic} production")

    return queries[:5]  # Limit to 5 queries


def _format_github_for_skill(github_data: dict[str, Any]) -> str:
    """Format GitHub research results for skill generation."""

    if not github_data or not github_data.get("success"):
        return "No GitHub research data available for analysis."

    repositories = github_data.get("repositories", [])
    code_results = github_data.get("code_results", [])

    if not repositories and not code_results:
        return "No GitHub repositories or code examples found for analysis."

    formatted_github = "## GitHub Code Analysis and Community Insights\n\n"

    # Add repository analysis
    if repositories:
        formatted_github += "### Notable Repositories and Projects\n\n"
        formatted_github += f"Found {len(repositories)} relevant repositories on GitHub:\n\n"

        for i, repo in enumerate(repositories[:8], 1):  # Top 8 repos
            formatted_github += f"**{i}. {repo.get('full_name', 'Unknown Repo')}**\n"
            if repo.get("description"):
                formatted_github += f"   {repo['description']}\n"
            formatted_github += f"   - ⭐ {repo.get('stars', 0)} stars, 🍴 {repo.get('forks', 0)} forks\n"
            if repo.get("language"):
                formatted_github += f"   - Language: {repo['language']}\n"
            if repo.get("topics"):
                topics_str = ", ".join(repo["topics"][:5])  # Limit topics
                formatted_github += f"   - Topics: {topics_str}\n"
            formatted_github += "\n"

    # Add code analysis
    if code_results:
        formatted_github += "### Code Implementation Patterns\n\n"
        formatted_github += f"Found {len(code_results)} relevant code examples:\n\n"

        # Group by repository for better organization
        repo_groups = {}
        for result in code_results:
            repo = result.get("repository", "Unknown")
            if repo not in repo_groups:
                repo_groups[repo] = []
            repo_groups[repo].append(result)

        for repo_name, results in list(repo_groups.items())[:5]:  # Top 5 repos with code
            formatted_github += f"**Repository: {repo_name}**\n\n"

            for result in results[:3]:  # Top 3 files per repo
                # file_name = result.get("name", "Unknown")  # Unused for now
                file_path = result.get("path", "")
                score = result.get("score", 0)

                formatted_github += f"- `{file_path}` (Relevance: {score:.2f})\n"

                # Include code preview if available
                if result.get("content_preview"):
                    content = result["content_preview"]
                    # Truncate for readability
                    if len(content) > 300:
                        content = content[:300] + "..."
                    formatted_github += f"  ```\n{content}\n  ```\n"

            formatted_github += "\n"

    # Add insights section
    formatted_github += "### Community Implementation Insights\n\n"

    if repositories:
        # Analyze technology trends
        languages = {}
        total_stars = 0

        for repo in repositories:
            lang = repo.get("language")
            if lang:
                languages[lang] = languages.get(lang, 0) + 1
            total_stars += repo.get("stars", 0)

        if languages:
            top_languages = sorted(languages.items(), key=lambda x: x[1], reverse=True)[:3]
            formatted_github += (
                f"**Popular Languages**: {', '.join([f'{lang} ({count} repos)' for lang, count in top_languages])}\n\n"
            )

        if total_stars > 0:
            formatted_github += f"**Community Interest**: {total_stars} total stars across analyzed repositories\n\n"

    formatted_github += "*GitHub analysis conducted on: 2025-12-02*\n"
    formatted_github += f"*Repositories analyzed: {len(repositories)}*\n"
    formatted_github += f"*Code examples found: {len(code_results)}*\n"

    return formatted_github


async def _perform_arxiv_research(topic: str) -> dict[str, Any]:
    """Perform arXiv research for the given topic."""

    try:
        from .adn_arxiv_research import adn_arxiv_research

        # Generate research queries based on topic
        queries = _generate_arxiv_queries(topic)

        all_papers = []

        # Search for academic papers
        for query in queries[:3]:  # Limit to 3 searches
            logger.info(f"Searching arXiv: {query}")

            paper_result = await (adn_arxiv_research.fn if hasattr(adn_arxiv_research, "fn") else adn_arxiv_research)(
                operation="search_papers",
                query=query,
                max_results=5,
                sort_by="relevance",
            )

            if paper_result.get("papers"):
                all_papers.extend(paper_result["papers"])

        # Remove duplicates based on arXiv ID
        seen_ids = set()
        unique_papers = []
        for paper in all_papers:
            paper_id = paper.get("arxiv_id")
            if paper_id and paper_id not in seen_ids:
                seen_ids.add(paper_id)
                unique_papers.append(paper)

        return {
            "success": True,
            "topic": topic,
            "papers": unique_papers[:15],  # Top 15 most relevant papers
            "total_papers_found": len(unique_papers),
            "search_timestamp": "2025-12-02",
        }

    except Exception as e:
        logger.error(f"arXiv research failed for topic '{topic}': {e}")
        return {
            "success": False,
            "error": str(e),
            "topic": topic,
            "suggestions": [
                "Check arXiv API availability",
                "Try simpler search terms",
                "Verify network connectivity",
            ],
        }


def _generate_arxiv_queries(topic: str) -> list[str]:
    """Generate targeted arXiv search queries for a topic."""

    topic_lower = topic.lower()

    # Base queries
    queries = [
        f'"{topic}"',
        f"{topic} review",
        f"{topic} survey",
    ]

    # Specialized queries based on topic
    if any(word in topic_lower for word in ["ai", "ml", "neural", "deep learning", "machine learning"]):
        queries.extend(
            [
                f"{topic} transformer",
                f"{topic} neural network",
                f"{topic} deep learning",
            ]
        )

    elif any(word in topic_lower for word in ["quantum", "physics", "chemistry", "biology"]):
        queries.extend(
            [
                f"{topic} quantum",
                f"{topic} computational",
                f"{topic} theoretical",
            ]
        )

    elif any(word in topic_lower for word in ["math", "mathematics", "algorithm"]):
        queries.extend(
            [
                f"{topic} algorithm",
                f"{topic} mathematical",
                f"{topic} proof",
            ]
        )

    elif any(word in topic_lower for word in ["security", "cryptography", "privacy"]):
        queries.extend(
            [
                f"{topic} cryptographic",
                f"{topic} security",
                f"{topic} privacy",
            ]
        )

    # Always include recent research
    queries.append(f"{topic} 2024")
    queries.append(f"{topic} 2025")

    return queries[:5]  # Limit to 5 queries


def _format_arxiv_for_skill(arxiv_data: dict[str, Any]) -> str:
    """Format arXiv research results for skill generation."""

    if not arxiv_data or not arxiv_data.get("success"):
        return "No arXiv research data available for analysis."

    papers = arxiv_data.get("papers", [])

    if not papers:
        return "No arXiv papers found for analysis."

    formatted_arxiv = "## Academic Research & Scholarly Analysis (arXiv)\n\n"

    # Group papers by recency and relevance
    recent_papers = []
    foundational_papers = []
    review_papers = []

    for paper in papers:
        title_lower = paper.get("title", "").lower()
        abstract_lower = paper.get("abstract", "").lower()

        # Classify papers
        if any(word in title_lower for word in ["survey", "review", "overview", "comprehensive"]):
            review_papers.append(paper)
        elif any(word in abstract_lower for word in ["we propose", "we present", "we introduce", "novel"]):
            recent_papers.append(paper)
        else:
            foundational_papers.append(paper)

    # Add review/survey papers first (most comprehensive)
    if review_papers:
        formatted_arxiv += "### Comprehensive Reviews & Surveys\n\n"
        for i, paper in enumerate(review_papers[:3], 1):
            formatted_arxiv += f"**{i}. {paper.get('title', 'Unknown Title')}**\n"
            formatted_arxiv += f"   Authors: {', '.join(paper.get('authors', [])[:3])}\n"

            abstract = paper.get("abstract", "")
            if len(abstract) > 300:
                abstract = abstract[:300] + "..."
            formatted_arxiv += f"   Abstract: {abstract}\n"

            if paper.get("arxiv_id"):
                formatted_arxiv += f"   arXiv: {paper['arxiv_id']} | PDF: {paper.get('pdf_url', '')}\n"

            categories = paper.get("categories", [])
            if categories:
                formatted_arxiv += f"   Categories: {', '.join(categories[:3])}\n"

            formatted_arxiv += "\n"

    # Add recent research papers
    if recent_papers:
        formatted_arxiv += "### Recent Research & Advances\n\n"
        for i, paper in enumerate(recent_papers[:4], 1):
            formatted_arxiv += f"**{i}. {paper.get('title', 'Unknown Title')}**\n"
            formatted_arxiv += f"   Authors: {', '.join(paper.get('authors', [])[:3])}\n"

            abstract = paper.get("abstract", "")
            if len(abstract) > 250:
                abstract = abstract[:250] + "..."
            formatted_arxiv += f"   Abstract: {abstract}\n"

            if paper.get("arxiv_id"):
                formatted_arxiv += f"   arXiv: {paper['arxiv_id']} | PDF: {paper.get('pdf_url', '')}\n"

            formatted_arxiv += "\n"

    # Add foundational papers
    if foundational_papers:
        formatted_arxiv += "### Foundational & Theoretical Work\n\n"
        for i, paper in enumerate(foundational_papers[:3], 1):
            formatted_arxiv += f"**{i}. {paper.get('title', 'Unknown Title')}**\n"
            formatted_arxiv += f"   Authors: {', '.join(paper.get('authors', [])[:3])}\n"

            abstract = paper.get("abstract", "")
            if len(abstract) > 200:
                abstract = abstract[:200] + "..."
            formatted_arxiv += f"   Abstract: {abstract}\n"

            if paper.get("arxiv_id"):
                formatted_arxiv += f"   arXiv: {paper['arxiv_id']} | PDF: {paper.get('pdf_url', '')}\n"

            formatted_arxiv += "\n"

    # Add research insights
    formatted_arxiv += "### Research Insights & Patterns\n\n"

    # Analyze publication patterns
    if papers:
        # Count papers by primary category
        categories = {}
        total_authors = 0
        author_counts = []

        for paper in papers:
            primary_cat = paper.get("primary_category", "")
            if primary_cat:
                categories[primary_cat] = categories.get(primary_cat, 0) + 1

            authors = paper.get("authors", [])
            total_authors += len(authors)
            author_counts.append(len(authors))

        if categories:
            top_categories = sorted(categories.items(), key=lambda x: x[1], reverse=True)[:3]
            formatted_arxiv += f"**Active Research Areas**: {', '.join([f'{cat} ({count} papers)' for cat, count in top_categories])}\n\n"

        if author_counts:
            avg_authors = sum(author_counts) / len(author_counts)
            formatted_arxiv += f"**Collaboration Patterns**: Average {avg_authors:.1f} authors per paper\n\n"

    formatted_arxiv += "*arXiv research analysis conducted on: 2025-12-02*\n"
    formatted_arxiv += f"*Academic papers analyzed: {len(papers)}*\n"

    return formatted_arxiv


async def _perform_tvtropes_research(topic: str) -> dict[str, Any]:
    """Perform TV Tropes research for narrative patterns."""

    try:
        from .adn_tvtropes_research import adn_tvtropes_research

        # Determine the most appropriate research type based on topic
        research_type = _determine_tvtropes_research_type(topic)

        if research_type == "character_archetypes":
            result = await (
                adn_tvtropes_research.fn if hasattr(adn_tvtropes_research, "fn") else adn_tvtropes_research
            )(operation="character_archetypes", query=topic, max_results=5)
        elif research_type == "plot_structures":
            result = await (
                adn_tvtropes_research.fn if hasattr(adn_tvtropes_research, "fn") else adn_tvtropes_research
            )(operation="plot_structures", query=topic, max_results=5)
        elif research_type == "narrative_analysis":
            result = await (
                adn_tvtropes_research.fn if hasattr(adn_tvtropes_research, "fn") else adn_tvtropes_research
            )(operation="narrative_analysis", query=topic, max_results=5)
        else:
            result = await (
                adn_tvtropes_research.fn if hasattr(adn_tvtropes_research, "fn") else adn_tvtropes_research
            )(operation="search_tropes", query=topic, max_results=5)

        return {
            "success": True,
            "topic": topic,
            "research_type": research_type,
            "tvtropes_data": result,
            "search_timestamp": "2025-12-02",
            "compliance_note": "TV Tropes research respects terms of service. Manual verification recommended.",
        }

    except Exception as e:
        logger.error(f"TV Tropes research failed for topic '{topic}': {e}")
        return {
            "success": False,
            "error": str(e),
            "topic": topic,
            "suggestion": "TV Tropes research failed. Visit tvtropes.org manually for narrative research.",
        }


def _is_narrative_topic(topic: str) -> bool:
    """Determine if a topic is related to narrative/writing/creative content."""

    topic_lower = topic.lower()

    narrative_keywords = [
        "writing",
        "story",
        "narrative",
        "character",
        "plot",
        "storytelling",
        "creative",
        "fiction",
        "novel",
        "screenplay",
        "script",
        "literature",
        "archetype",
        "trope",
        "genre",
        "myth",
        "hero",
        "villain",
        "protagonist",
        "narrative",
        "structure",
        "pacing",
        "tension",
        "conflict",
        "resolution",
        "media",
        "film",
        "tv",
        "television",
        "cinema",
        "book",
        "author",
    ]

    return any(keyword in topic_lower for keyword in narrative_keywords)


def _determine_tvtropes_research_type(topic: str) -> str:
    """Determine the most appropriate TV Tropes research type for a topic."""

    topic_lower = topic.lower()

    if any(word in topic_lower for word in ["character", "archetype", "personality", "role"]):
        return "character_archetypes"
    elif any(word in topic_lower for word in ["plot", "structure", "story", "narrative"]):
        return "plot_structures"
    elif any(word in topic_lower for word in ["writing", "creative", "fiction", "storytelling"]):
        return "narrative_analysis"
    else:
        return "search_tropes"


def _format_tvtropes_for_skill(tvtropes_data: dict[str, Any]) -> str:
    """Format TV Tropes research results for skill generation."""

    if not tvtropes_data or not tvtropes_data.get("success"):
        return "No TV Tropes research data available for analysis."

    research_type = tvtropes_data.get("research_type", "general")
    tvtropes_result = tvtropes_data.get("tvtropes_data", {})

    formatted_tropes = "## Narrative Patterns & Storytelling Insights (TV Tropes Research)\n\n"

    formatted_tropes += f"**Research Focus**: {research_type.replace('_', ' ').title()}\n\n"

    # Add strong compliance disclaimer
    formatted_tropes += "⚠️ **COMPLIANCE NOTICE**: TV Tropes content cannot be scraped or reproduced. "
    formatted_tropes += (
        "This analysis provides research guidance only. Visit TV Tropes directly for complete information.\n\n"
    )

    # Format based on research type
    if research_type == "character_archetypes":
        archetypes = tvtropes_result.get("character_archetypes", [])
        if archetypes:
            formatted_tropes += "### Character Archetypes & Personality Patterns\n\n"
            for archetype in archetypes[:5]:
                formatted_tropes += f"**{archetype.get('archetype', 'Unknown')}**\n"
                formatted_tropes += f"   {archetype.get('description', '')}\n"
                traits = archetype.get("traits", [])
                if traits:
                    formatted_tropes += f"   *Key Traits*: {', '.join(traits)}\n"
                examples = archetype.get("examples", [])
                if examples:
                    formatted_tropes += f"   *Examples*: {', '.join(examples[:3])}\n"
                formatted_tropes += "\n"

    elif research_type == "plot_structures":
        structures = tvtropes_result.get("plot_structures", [])
        if structures:
            formatted_tropes += "### Plot Structures & Story Frameworks\n\n"
            for structure in structures[:5]:
                formatted_tropes += f"**{structure.get('structure', 'Unknown')}**\n"
                formatted_tropes += f"   {structure.get('description', '')}\n"
                formatted_tropes += f"   *Acts*: {structure.get('acts', 'N/A')}\n"
                applications = structure.get("applications", [])
                if applications:
                    formatted_tropes += f"   *Commonly Used In*: {', '.join(applications)}\n"
                formatted_tropes += "\n"

    elif research_type == "narrative_analysis":
        analysis = tvtropes_result.get("narrative_analysis", {})
        patterns = analysis.get("patterns_found", [])
        if patterns:
            formatted_tropes += "### Narrative Patterns & Techniques\n\n"
            for pattern in patterns[:5]:
                formatted_tropes += f"**{pattern.get('pattern', 'Unknown')}**\n"
                formatted_tropes += f"   {pattern.get('description', '')}\n"
                applications = pattern.get("applications", [])
                if applications:
                    formatted_tropes += f"   *Applications*: {', '.join(applications)}\n"
                formatted_tropes += "\n"

    else:  # general search
        results = tvtropes_result.get("results", [])
        if results:
            formatted_tropes += "### Relevant Tropes & Concepts\n\n"
            for result in results[:5]:
                formatted_tropes += f"**{result.get('name', 'Unknown Trope')}**\n"
                formatted_tropes += f"   {result.get('description', '')}\n"
                formatted_tropes += f"   *Category*: {result.get('category', 'General')}\n"
                formatted_tropes += f"   *Relevance*: {result.get('relevance_score', 0):.2f}\n\n"

    # Add research methodology note
    formatted_tropes += "### Research Methodology Notes\n\n"
    formatted_tropes += "- TV Tropes research conducted with respect for terms of service\n"
    formatted_tropes += "- Rate limiting and human-like delays implemented\n"
    formatted_tropes += "- No content scraping or automated extraction performed\n"
    formatted_tropes += "- Results provided as research guidance and inspiration\n"
    formatted_tropes += "- Manual verification at tvtropes.org strongly recommended\n\n"

    formatted_tropes += "*TV Tropes research conducted on: 2025-12-02*\n"
    formatted_tropes += "*All analysis respects TV Tropes terms of service*\n"

    return formatted_tropes
