"""Static templates used by the skill creator service."""

from __future__ import annotations

import datetime
from textwrap import dedent

CONFIDENCE_LABELS = {
    "low": "🔴 Low",
    "medium": "🟡 Medium",
    "high": "🟢 High",
}


def today_iso() -> str:
    """Return today's date in ISO format."""
    return datetime.date.today().isoformat()


def render_skill_markdown(
    name: str,
    title: str,
    description: str,
    *,
    allowed_tools: list[str] | None = None,
    license_: str | None = None,
    metadata: dict[str, str] | None = None,
) -> str:
    """Render the SKILL.md body following Anthropic's official skills specification."""

    description_text = (
        description or "[TODO] Add a concise description explaining what this skill does and when Claude should use it."
    )
    allowed_tools = [tool for tool in (allowed_tools or []) if tool]

    frontmatter_lines = ["---", f"name: {name}", f"description: {description_text}"]
    if allowed_tools:
        frontmatter_lines.append("allowed-tools:")
        for tool in allowed_tools:
            frontmatter_lines.append(f"  - {tool}")
    if license_:
        frontmatter_lines.append(f"license: {license_}")
    if metadata:
        frontmatter_lines.append("metadata:")
        for key, value in metadata.items():
            frontmatter_lines.append(f"  {key}: {value}")
    frontmatter_lines.append("---")

    body = f"""# {title}

## Overview

{description_text}

## Usage Instructions

This skill provides specialized knowledge and workflows for {title.lower()}. Use it when you need expert guidance on this topic.

## Getting Started

1. Review the main content below to understand the skill's capabilities
2. Apply the patterns and best practices to your specific use case
3. Reference examples and templates as needed

## Content

[Skill content goes here - replace with actual implementation details]

---
*Generated by Advanced Memory MCP - Anthropic Skills Spec Compliant*
"""
    return "\n".join(frontmatter_lines) + "\n" + dedent(body).strip() + "\n"


def render_core_guidance(content: str | None = None) -> str:
    """Render the core-guidance module."""
    body = content or (
        "# Core Guidance\n\nReplace this section with validated, imperative instructions once research is complete."
    )
    return (
        dedent(
            f"""# Core Guidance (Legacy Template)

**Confidence**: 🔴 LOW
**Last captured**: {today_iso()}

> This module preserves the original skill instructions prior to modular conversion.
> Treat every section as unverified until you complete the research checklist and add dated sources.

---

{body}
"""
        ).strip()
        + "\n"
    )


def render_known_gaps() -> str:
    """Render the known-gaps module."""
    return (
        dedent(
            """# Known Gaps & Validation Tasks

## Critical gaps
- ❌ Fresh web research has not been captured after the Oct 2024 training cutoff.
- ❌ Source log has not been updated in the research checklist.
- ❌ Domain expert review pending.

## TODOs
1. Complete the research checklist and archive dated sources.
2. Update `modules/core-guidance.md` with verified guidance and confidence markers.
3. Refresh the status banner in `SKILL.md` once validation is complete.

## Notes
- Add additional items here as you uncover domain-specific gaps.
"""
        ).strip()
        + "\n"
    )


def render_research_checklist() -> str:
    """Render the research-checklist module."""
    return (
        dedent(
            f"""# Research Checklist

Follow these steps before trusting this skill:

1. Identify the freshness risk (APIs, frameworks, standards, or safety-critical topics).
2. Run targeted web searches (official docs, release notes, expert articles) dated {today_iso()[:4]} or newer.
3. Record each source with title, URL, and access date in the Source Log below.
4. Validate the legacy guidance inside [core-guidance.md](core-guidance.md) against the new sources.
5. Update the status banner in `SKILL.md` (status, last validated, confidence) once validation is complete.
6. Move confirmed instructions into dedicated topic modules and mark obsolete content for removal.
7. Document remaining unknowns in [known-gaps.md](known-gaps.md).

## Source Log
- _Add sources here with format:_ `- YYYY-MM-DD — Title (URL)`

> Tip: Use `adn_skills("distill_from_wikipedia", ...)`, `adn_skills("distill_from_arxiv", ...)`, and trusted web research to bootstrap validation.
"""
        ).strip()
        + "\n"
    )


def render_toc() -> str:
    """Render the module table of contents."""
    return (
        dedent(
            """# Module Guide

| Module | Purpose |
| --- | --- |
| [modules/core-guidance.md](modules/core-guidance.md) | Legacy guidance captured prior to fresh research. Review and update after validation. |
| [modules/known-gaps.md](modules/known-gaps.md) | Track missing evidence, unresolved questions, and validation tasks. |
| [modules/research-checklist.md](modules/research-checklist.md) | Required web research workflow before using this skill. |
"""
        ).strip()
        + "\n"
    )


def render_example_script(skill_name: str) -> str:
    """Render placeholder script content."""
    return (
        dedent(
            f"""#!/usr/bin/env python3
\"\"\"
Example helper script for {skill_name}

Replace with actual implementation or delete if not needed.
\"\"\"


def main() -> None:
    print("This is an example script placeholder.")


if __name__ == "__main__":
    main()
"""
        ).strip()
        + "\n"
    )


def render_example_reference(title: str) -> str:
    """Render placeholder reference content."""
    return (
        dedent(
            f"""# Reference Documentation for {title}

Replace with domain-specific documentation or delete if not needed.
"""
        ).strip()
        + "\n"
    )


def render_example_asset() -> str:
    """Render placeholder asset content."""
    return "Example asset placeholder. Replace with templates, fonts, or other output resources.\n"
